export const names = {
    Abomination: "Abomination (Emil Blonsky)",
    Ajak: "Ajak",
    AlexanderPierce: "Alexander Pierce",
    AncientOne: "Ancient One",
    AnneMarieHoag: "Anne Marie Hoag",
    AntMan: "Ant-Man (Scott Lang)",
    BaronMordo: "Baron Mordo (Karl Mordo)",
    BaronZemo: "Baron Zemo (Helmut Zemo)",
    BettyRoss: "Betty Ross",
    BlackKnight: "Black Knight (Dane Whitman)",
    BlackPanther: "Black Panther",
    BlackPantherShuri: "Black Panther (Shuri)",
    BlackWidowYelena: "Black Widow (Yelena Belova)",
    BlackWidow: "Black Widow/Natasha Romanoff (MAA)",
    Bucky: "Bucky",
    CaptainAmerica: "Captain America/Steve Rogers (MAA)",
    CaptainMarvel: "Captain Marvel (Carol Danvers)",
    DoctorOctopus: "Doctor Octopus",
    Drax: "Drax",
    Druig: "Druig",
    DumDumDugan: "Dum Dum Dugan",
    Electro: "Electro",
    Executioner: "Executioner (Skurge)",
    Falcon: "Falcon/Sam Wilson (MAA)",
    GabeJones: "Gabe Jones",
    Gamora: "Gamora",
    Gilgamesh: "Gilgamesh",
    Goliath: "Goliath (Bill Foster)",
    Grandmaster: "Grandmaster",
    GreenGoblin: "Green Goblin (Norman Osborn)",
    Groot: "Groot",
    HankPym: "Hank Pym",
    HappyHogan: "Happy Hogan",
    Hawkeye: "Hawkeye/Clint Barton (MAA)",
    Hela: "Hela",
    Hulk: "Hulk (Marvel: Avengers Alliance)",
    Ikaris: "Ikaris",
    IronMan: "Iron Man/Tony Stark (MAA)",
    IronPatriot: "Iron Patriot (James Rhodes)",
    JaneFoster: "Jane Foster",
    JimPaxton: "Jim Paxton",
    JimmyWoo: "Jimmy Woo",
    JustinHammer: "Justin Hammer",
    Killmonger: "Killmonger",
    Korath: "Korath",
    Loki: "Loki",
    Makkari: "Makkari",
    Mantis: "Mantis",
    MariaHill: "Maria Hill",
    MayParker: "May Parker",
    MsAmerica: "Ms.America (America Chavez)",
    Mysterio: "Mysterio",
    Nakia: "Nakia",
    Nebula: "Nebula",
    NickFury: "Nick Fury",
    ObadiahStane: "Obadiah Stane",
    Odin: "Odin",
    Okoye: "Okoye",
    PeggyCarter: "Peggy Carter",
    PepperPotts: "Pepper Potts",
    PhilCoulson: "Phil Coulson (Phil Coulson)",
    RedGuardian: "Red Guardian (Alexei Shostakov)",
    RedSkull: "Red Skull",
    RocketRaccoon: "Rocket Raccoon",
    ScarletWitch: "Scarlet Witch",
    Sersi: "Sersi",
    SharonCarter: "Sharon Carter",
    Shocker: "Shocker (Herman Schultz)",
    Sif: "Sif",
    SpiderMan: "Spider-Man (Peter Parker)",
    Sprite: "Sprite",
    Starhawk: "Starhawk (Stakar Ogord)",
    StarLord: "Star-Lord (Peter Quill)",
    StephenStrange: "Stephen Strange",
    SupremeIntelligence: "Supreme Intelligence",
    Talos: "Talos",
    Taskmaster: "Taskmaster",
    ThaddeusRoss: "Thaddeus Ross",
    Thanos: "Thanos",
    TheCollector: "The Collector (Taneleer Tivan)",
    Thena: "Thena",
    Thor: "Thor",
    ThunderboltRoss: "Thunderbolt Ross",
    Ultron: "Ultron",
    Vision: "Vision",
    Vulture: "Vulture (Adrian Toomes)",
    WarMachine: "War Machine (James Rhodes)",
    wasp: "wasp",
    Whiplash: "Whiplash (Anton Vanko)",
    WinterSoldier: "Winter Soldier",
    Wong: "Wong",
    Yellowjacket: "Yellowjacket (Rita DeMara)",
    Yondu: "Yondu"
}